version: '3.8'

services:
  hbase:
    image: dajobe/hbase
    container_name: hbase
    ports:
      - "16000:16000"  # HBase Master
      - "16010:16010"  # HBase Master Web UI
      - "16020:16020"  # HBase RegionServer
      - "16030:16030"  # HBase RegionServer Web UI
      - "2181:2181"    # ZooKeeper
      - "9090:9090"   # Thrift server
    volumes:
      - hbase_data:/data
    environment:
      HBASE_MANAGES_ZK: 'true'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "16010"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hbase_data:

networks:
  default:
    name: hbase-network